name: Enforce Tag on Pull Request to Main

on:
  pull_request:
    branches:
      - main

jobs:
  enforce-tag:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check for Tag in PR
        id: check-tag
        shell: bash
        run: |
          PR_TITLE="${{ github.event.pull_request.title }}"
          PR_BODY="${{ github.event.pull_request.body }}"
          TAG_REGEX='v[0-9]+\.[0-9]+\.[0-9]+'

          if echo "$PR_TITLE $PR_BODY" | grep -qE "$TAG_REGEX"; then
              TAG=$(echo "$PR_TITLE $PR_BODY" | grep -oE "$TAG_REGEX" | head -n 1)
              echo "Tag found: $TAG"
              echo "TAG=$TAG" >> $GITHUB_ENV
          else
              echo "No valid tag found in the PR."
              exit 1
          fi

      - name: Create and Push Tag
        shell: bash
        env:
            TAG: ${{ env.TAG }}
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          run: |
            git config user.name "GitHub Actions"
            git config user.email "actions@github.com"
            git fetch --tags
        
            if git rev-parse "$TAG" >/dev/null 2>&1; then
                echo "Tag $TAG already exists. No action needed."
            else
                echo "Creating and pushing tag: $TAG"
                git tag "$TAG"
                git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }} "$TAG"
            fi

