name: Enforce Tag on Commit Messages

on:
  pull_request:
    branches:
      - testing

jobs:
  check-tag:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check for tag in commit message
        run: |
          TAG_REGEX='v[0-9]+\.[0-9]+\.[0-9]+'
          COMMITS=$(git log origin/main..HEAD --pretty=format:"%s")
          echo "Commits to check:"
          echo "$COMMITS"

          if ! echo "$COMMITS" | grep -qE "$TAG_REGEX"; then
            echo "Error: Commit messages must include a valid version tag (e.g., v1.0.0)."
            exit 1
          fi
