name: Get Latest Merged Pull Request on Push

on:
  push:
    branches:
      - main

jobs:
  get-latest-merged-pr:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Configurar GitHub CLI
      - name: Configurar GitHub CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y gh

      # Step 2: Autenticar GitHub CLI
      - name: Autenticar GitHub CLI
        run: echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token

      # Step 3: Obtener el PR más reciente fusionado
      - name: Obtener el PR más reciente fusionado
        id: get_pr
        run: |
          PR=$(gh pr list --state merged --base main --sort updated --limit 1 --json title,number,mergedAt,url --jq '.[0]')
          echo "Título del PR: $(echo $PR | jq -r '.title')"
          echo "Número del PR: $(echo $PR | jq -r '.number')"
          echo "Fecha de fusión: $(echo $PR | jq -r '.mergedAt')"
          echo "URL del PR: $(echo $PR | jq -r '.url')"
          echo "pr_title=$(echo $PR | jq -r '.title')" >> $GITHUB_ENV
          echo "pr_number=$(echo $PR | jq -r '.number')" >> $GITHUB_ENV
          echo "pr_merged_at=$(echo $PR | jq -r '.mergedAt')" >> $GITHUB_ENV
          echo "pr_url=$(echo $PR | jq -r '.url')" >> $GITHUB_ENV

      # Step 4: Mostrar detalles del PR
      - name: Mostrar detalles del PR
        run: |
          echo "Último PR fusionado:"
          echo "Título: ${{ env.pr_title }}"
          echo "Número: ${{ env.pr_number }}"
          echo "Fecha de fusión: ${{ env.pr_merged_at }}"
          echo "URL: ${{ env.pr_url }}"
